# Generated by Django 4.2.6 on 2024-02-26 11:17

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_sliders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sliders",
            name="paragraph_slider",
            field=wagtail.fields.RichTextField(default="Insira aqui o conteúdo do curso"),
        ),
    ]
